# Generated by Django 3.1.1 on 2025-01-16 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_client', models.CharField(max_length=255, verbose_name='ID клиета от мерчанта')),
                ('email', models.CharField(max_length=255, verbose_name='Почта')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('ip', models.CharField(max_length=50, verbose_name='IP адресс')),
                ('billing_addres', models.CharField(blank=True, max_length=100, null=True, verbose_name='Физический адресс проживания')),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер телефона')),
                ('ban', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Сущность клиента',
                'verbose_name_plural': 'Сущность клиента',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=255, unique=True)),
                ('provider_invoice_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_by_currency', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_by_currency_merchant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_by_currency_trader', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_by_currency_provider', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(max_length=255)),
                ('county', models.CharField(max_length=255, verbose_name='Страна')),
                ('currency', models.CharField(max_length=255, verbose_name='Валюта')),
                ('webhook', models.CharField(max_length=255, verbose_name='URL уведомлений')),
                ('holder_name_rec', models.CharField(max_length=255)),
                ('number_rec', models.CharField(blank=True, max_length=255, null=True)),
                ('bank', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Completed'), ('expired', 'Expired'), ('dispute', 'Dispute'), ('canceled', 'Canceled')], default='pending', max_length=50)),
                ('type', models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw')], max_length=50)),
                ('rate', models.FloatField(default=0.0, verbose_name='Курс')),
                ('decode_holder_name_client', models.CharField(blank=True, max_length=255, null=True)),
                ('decode_number_client', models.CharField(blank=True, max_length=255, null=True)),
                ('decode_bank_client', models.CharField(blank=True, max_length=255, null=True)),
                ('decode_expiration_date_card_client', models.DateField(blank=True, null=True)),
                ('decode_cvv_client', models.CharField(blank=True, max_length=4, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('media_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на S3')),
                ('success_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Редирект при успешной оплате ECOM')),
                ('failed_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Редирект при ошибки оплаты ECOM')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Сущность сделки',
                'verbose_name_plural': 'Сущность сделки',
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('balance', models.FloatField(default=0.0, verbose_name='Баланс')),
                ('hash_api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='API KEY')),
                ('status', models.BooleanField(default=False, verbose_name='Активно?')),
                ('total_settl', models.FloatField(default=0.0, verbose_name='Сколько было выводов')),
                ('sla_on_trade', models.IntegerField(default=15, verbose_name='Минуты на оплату')),
                ('sla_on_appeals', models.IntegerField(default=30, verbose_name='Минуты на решение спора')),
                ('max_amount_sla', models.IntegerField(default=150, verbose_name='Максимальная сумма в $ в которой закрывается спор без ответа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Сущность мерчанта',
                'verbose_name_plural': 'Сущность мерчанта',
            },
        ),
        migrations.CreateModel(
            name='SubMerchantAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('SUPPORT', 'Support'), ('BOOKER', 'Booker')], max_length=50, verbose_name='Роль суб. аккаунта мерча')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('merchant_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.merchant', verbose_name='Аккаунт мерчанта')),
                ('user_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_merchant', to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт пользователя')),
            ],
            options={
                'verbose_name': 'Сущность суб. аккаунта мерча',
                'verbose_name_plural': 'Сущность суб. аккаунта мерча',
            },
        ),
    ]
