# Generated by Django 3.1.1 on 2025-01-16 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trader', '0001_initial'),
        ('referal', '0001_initial'),
        ('merchant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trader.group', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='referal_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='referal.referaluser', verbose_name='ID реферала'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='user_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant', to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт пользователя'),
        ),
        migrations.AddField(
            model_name='deal',
            name='client_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='merchant.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='deal',
            name='creds_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trader.credstrader', verbose_name='Креды трейдера'),
        ),
        migrations.AddField(
            model_name='deal',
            name='provider_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trader.provider', verbose_name='Провайдер'),
        ),
        migrations.AddField(
            model_name='deal',
            name='responsible_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trader.trader', verbose_name='Трейдер'),
        ),
        migrations.AddField(
            model_name='deal',
            name='source_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.merchant', verbose_name='Мерчант'),
        ),
    ]