# Generated by Django 5.1.7 on 2025-03-26 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchant', '0001_initial'),
        ('referal', '0001_initial'),
        ('trader', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='creds_id',
            field=models.ForeignKey(blank=True, db_column='creds_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='trader.credstrader', verbose_name='Креды трейдера'),
        ),
        migrations.AddField(
            model_name='deal',
            name='provider_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trader.provider', verbose_name='Провайдер'),
        ),
        migrations.AddField(
            model_name='deal',
            name='responsible_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trader.trader', verbose_name='Трейдер'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trader.group', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='referal_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='referal.referaluser', verbose_name='ID реферала'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='user_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant', to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт пользователя'),
        ),
        migrations.AddField(
            model_name='deal',
            name='source_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.merchant', verbose_name='Мерчант'),
        ),
        migrations.AddField(
            model_name='submerchantaccount',
            name='merchant_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.merchant', verbose_name='Аккаунт мерчанта'),
        ),
        migrations.AddField(
            model_name='submerchantaccount',
            name='user_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_merchant', to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт пользователя'),
        ),
    ]
