# Generated by Django 5.1.7 on 2025-03-20 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_useraccounts_groups_and_more'),
        ('merchant', '0002_auto_20250116_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='user_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant', to='accounts.useraccounts', verbose_name='Аккаунт пользователя'),
        ),
        migrations.AlterField(
            model_name='submerchantaccount',
            name='user_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_merchant', to='accounts.useraccounts', verbose_name='Аккаунт пользователя'),
        ),
    ]
