# Generated by Django 5.1.7 on 2025-03-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccounts',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MERCHANT', 'Merchant'), ('TRADER', 'Trader')], default='MERCHANT', max_length=10),
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='user_accounts_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='user_accounts_permissions', to='auth.permission'),
        ),
    ]
