# Generated by Django 5.1.7 on 2025-03-21 04:30

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('merchant', '__first__'),
        ('trader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='reports/', verbose_name='Документ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Сущность документов',
                'verbose_name_plural': 'Сущность документов',
            },
        ),
        migrations.CreateModel(
            name='SupportUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, verbose_name='Почта')),
                ('hash_password', models.CharField(max_length=255, verbose_name='Хешированный пароль')),
                ('rating', models.FloatField(default=0.0, verbose_name='Рейтинг')),
                ('reward', models.FloatField(default=0.0, verbose_name='KPI к стаб, оплате')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_user', to='accounts.useraccounts', verbose_name='Аккаунт пользователя')),
            ],
            options={
                'verbose_name': 'Сущность пользователя поддержки',
                'verbose_name_plural': 'Сущность пользователя поддержки',
            },
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=255, unique=True)),
                ('invoice_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.FloatField(default=0.0, verbose_name='Стоимость')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Completed'), ('expired', 'Expired'), ('dispute', 'Dispute'), ('canceled', 'Canceled')], default='pending', max_length=50)),
                ('expiration_at', models.DateTimeField(blank=True, null=True)),
                ('documents', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('provider_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trader.provider', verbose_name='Провайдер')),
                ('responsible_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trader.trader', verbose_name='Трейдер')),
                ('source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.merchant', verbose_name='Мерчант')),
                ('sup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.supportuser', verbose_name='Пользователь поддержки')),
            ],
            options={
                'verbose_name': 'Сущность запроса в службу поддержки',
                'verbose_name_plural': 'Сущность запроса в службу поддержки',
            },
        ),
    ]
